[tools]
# CLI tools
"github:cli/cli" = "2.97.0"
"pinact" = "4.1.1"
"npm:@openai/codex" = "0.149.0"
"neovim" = "0.12.4"
"zellij" = "0.44.3"
"python" = "3.14.7"
"ripgrep" = "15.2.0"
"uv" = "0.12.5"

[settings]
experimental = true
